version: "2"
services:
  web:
    image: tenpo-test-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 6080:6080
    depends_on:
      - db


  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRES_PASSWORD=Elohim@123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=public
